sonar.exclusions=packages/database/prisma/migrations/**
sonar.sourceEncoding=UTF-8
sonar.issue.ignore.multicriteria=richTextEditor
sonar.issue.ignore.multicriteria.richTextEditor.ruleKey=typescript:S6819
sonar.issue.ignore.multicriteria.richTextEditor.resourceKey=apps/web/src/components/WhatsappText.tsx
